config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :investment_contract_dets
  resources :car_rental_contract_dets
  resources :the_drivers
  resources :investment_contracts
  resources :car_rental_contracts
  resources :members
  resources :customers
  resources :drivers
  resources :cars
  resources :model_cars
  resources :brands
  devise_for :admins
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :model_cars
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :model_car
  has_many :car_rental_contract_dets
  has_many :car_rental_contracts, :through => :car_rental_contract_dets
# thuc the yeu investment_contract_dets
  has_many :investment_contract_dets
  has_many :investment_contracts, :through => :investment_contract_dets
end

app/models/car_rental_contract.rb
class CarRentalContract < ApplicationRecord
  has_many :customers
  has_many :car_rental_contract_dets
  has_many :cars, :through => :car_rental_contract_dets
  has_many :passenger
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :car_rental_contract
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :car_rental_contract_dets
  has_many :the_drivers
  has_many :model_cars, :through => :the_drivers
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :investment_contracts
end

app/models/model_car.rb
class ModelCar < ApplicationRecord
  belongs_to :brand
  has_many :cars
  has_many :the_drivers
  has_many :drivers, :through => :the_drivers
end

app/models/passenger.rb
class Passenger < ApplicationRecord
end

app/models/the_driver.rb
class TheDriver < ApplicationRecord
  belongs_to :driver
  belongs_to :model_car
end

app/controllers/car_rental_contracts_controller.rb
class CarRentalContractsController < ApplicationController
  before_action :set_car_rental_contract, only: [:show, :edit, :update, :destroy]

  # GET /car_rental_contracts
  # GET /car_rental_contracts.json
  def index
    @car_rental_contracts = CarRentalContract.all
  end

  # GET /car_rental_contracts/1
  # GET /car_rental_contracts/1.json
  def show
  end

  # GET /car_rental_contracts/new
  def new
    @car_rental_contract = CarRentalContract.new
  end

  # GET /car_rental_contracts/1/edit
  def edit
  end

  # POST /car_rental_contracts
  # POST /car_rental_contracts.json
  def create
    @car_rental_contract = CarRentalContract.new(car_rental_contract_params)

    respond_to do |format|
      if @car_rental_contract.save
        format.html { redirect_to @car_rental_contract, notice: 'Car rental contract was successfully created.' }
        format.json { render :show, status: :created, location: @car_rental_contract }
      else
        format.html { render :new }
        format.json { render json: @car_rental_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_rental_contracts/1
  # PATCH/PUT /car_rental_contracts/1.json
  def update
    respond_to do |format|
      if @car_rental_contract.update(car_rental_contract_params)
        format.html { redirect_to @car_rental_contract, notice: 'Car rental contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_rental_contract }
      else
        format.html { render :edit }
        format.json { render json: @car_rental_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_rental_contracts/1
  # DELETE /car_rental_contracts/1.json
  def destroy
    @car_rental_contract.destroy
    respond_to do |format|
      format.html { redirect_to car_rental_contracts_url, notice: 'Car rental contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_rental_contract
      @car_rental_contract = CarRentalContract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_rental_contract_params
      params.require(:car_rental_contract).permit(:rDate, :rContent, :rValue)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/car_rental_contracts_helper.rb
module CarRentalContractsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/model_cars_helper.rb
module ModelCarsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/the_drivers_helper.rb
module TheDriversHelper
end

app/views/car_rental_contracts/_form.html.erb
<%= form_with(model: car_rental_contract, local: true) do |form| %>
  <% if car_rental_contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car_rental_contract.errors.count, "error") %> prohibited this car_rental_contract from being saved:</h2>

      <ul>
      <% car_rental_contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rDate %>
    <%= form.date_select :rDate %>
  </div>

  <div class="field">
    <%= form.label :rContent %>
    <%= form.text_area :rContent %>
  </div>

  <div class="field">
    <%= form.label :rValue %>
    <%= form.text_field :rValue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/car_rental_contracts/edit.html.erb
<h1>Editing Car Rental Contract</h1>

<%= render 'form', car_rental_contract: @car_rental_contract %>

<%= link_to 'Show', @car_rental_contract %> |
<%= link_to 'Back', car_rental_contracts_path %>

app/views/car_rental_contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Car Rental Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Rdate</th>
      <th>Rcontent</th>
      <th>Rvalue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_rental_contracts.each do |car_rental_contract| %>
      <tr>
        <td><%= car_rental_contract.rDate %></td>
        <td><%= car_rental_contract.rContent %></td>
        <td><%= car_rental_contract.rValue %></td>
        <td><%= link_to 'Show', car_rental_contract %></td>
        <td><%= link_to 'Edit', edit_car_rental_contract_path(car_rental_contract) %></td>
        <td><%= link_to 'Destroy', car_rental_contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car Rental Contract', new_car_rental_contract_path %>

app/views/car_rental_contracts/new.html.erb
<h1>New Car Rental Contract</h1>

<%= render 'form', car_rental_contract: @car_rental_contract %>

<%= link_to 'Back', car_rental_contracts_path %>

app/views/car_rental_contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rdate:</strong>
  <%= @car_rental_contract.rDate %>
</p>

<p>
  <strong>Rcontent:</strong>
  <%= @car_rental_contract.rContent %>
</p>

<p>
  <strong>Rvalue:</strong>
  <%= @car_rental_contract.rValue %>
</p>

<%= link_to 'Edit', edit_car_rental_contract_path(@car_rental_contract) %> |
<%= link_to 'Back', car_rental_contracts_path %>