config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :investment_contract_dets
  resources :car_rental_contract_dets
  resources :the_drivers
  resources :investment_contracts
  resources :car_rental_contracts
  resources :members
  resources :customers
  resources :drivers
  resources :cars
  resources :model_cars
  resources :brands
  devise_for :admins
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :model_cars
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :model_car
  has_many :car_rental_contract_dets
  has_many :car_rental_contracts, :through => :car_rental_contract_dets
# thuc the yeu investment_contract_dets
  has_many :investment_contract_dets
  has_many :investment_contracts, :through => :investment_contract_dets
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :car_rental_contract
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :car_rental_contract_dets
  has_many :the_drivers
  has_many :model_cars, :through => :the_drivers
end

app/models/investment_contract_det.rb
class InvestmentContractDet < ApplicationRecord
  belongs_to :investment_contract
  belongs_to :car
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :investment_contracts
end

app/models/model_car.rb
class ModelCar < ApplicationRecord
  belongs_to :brand
  has_many :cars
  has_many :the_drivers
  has_many :drivers, :through => :the_drivers
end

app/models/passenger.rb
class Passenger < ApplicationRecord
end

app/models/the_driver.rb
class TheDriver < ApplicationRecord
  belongs_to :driver
  belongs_to :model_car
end

app/controllers/investment_contract_dets_controller.rb
class InvestmentContractDetsController < ApplicationController
  before_action :set_investment_contract_det, only: [:show, :edit, :update, :destroy]

  # GET /investment_contract_dets
  # GET /investment_contract_dets.json
  def index
    @investment_contract_dets = InvestmentContractDet.all
  end

  # GET /investment_contract_dets/1
  # GET /investment_contract_dets/1.json
  def show
  end

  # GET /investment_contract_dets/new
  def new
    @investment_contract_det = InvestmentContractDet.new
  end

  # GET /investment_contract_dets/1/edit
  def edit
  end

  # POST /investment_contract_dets
  # POST /investment_contract_dets.json
  def create
    @investment_contract_det = InvestmentContractDet.new(investment_contract_det_params)

    respond_to do |format|
      if @investment_contract_det.save
        format.html { redirect_to @investment_contract_det, notice: 'Investment contract det was successfully created.' }
        format.json { render :show, status: :created, location: @investment_contract_det }
      else
        format.html { render :new }
        format.json { render json: @investment_contract_det.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investment_contract_dets/1
  # PATCH/PUT /investment_contract_dets/1.json
  def update
    respond_to do |format|
      if @investment_contract_det.update(investment_contract_det_params)
        format.html { redirect_to @investment_contract_det, notice: 'Investment contract det was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment_contract_det }
      else
        format.html { render :edit }
        format.json { render json: @investment_contract_det.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investment_contract_dets/1
  # DELETE /investment_contract_dets/1.json
  def destroy
    @investment_contract_det.destroy
    respond_to do |format|
      format.html { redirect_to investment_contract_dets_url, notice: 'Investment contract det was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment_contract_det
      @investment_contract_det = InvestmentContractDet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_contract_det_params
      params.require(:investment_contract_det).permit(:idetContribDay)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/investment_contract_dets_helper.rb
module InvestmentContractDetsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/model_cars_helper.rb
module ModelCarsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/the_drivers_helper.rb
module TheDriversHelper
end

app/views/investment_contract_dets/_form.html.erb
<%= form_with(model: investment_contract_det, local: true) do |form| %>
  <% if investment_contract_det.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investment_contract_det.errors.count, "error") %> prohibited this investment_contract_det from being saved:</h2>

      <ul>
      <% investment_contract_det.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idetContribDay %>
    <%= form.date_select :idetContribDay %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investment_contract_dets/edit.html.erb
<h1>Editing Investment Contract Det</h1>

<%= render 'form', investment_contract_det: @investment_contract_det %>

<%= link_to 'Show', @investment_contract_det %> |
<%= link_to 'Back', investment_contract_dets_path %>

app/views/investment_contract_dets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investment Contract Dets</h1>

<table>
  <thead>
    <tr>
      <th>Idetcontribday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investment_contract_dets.each do |investment_contract_det| %>
      <tr>
        <td><%= investment_contract_det.idetContribDay %></td>
        <td><%= link_to 'Show', investment_contract_det %></td>
        <td><%= link_to 'Edit', edit_investment_contract_det_path(investment_contract_det) %></td>
        <td><%= link_to 'Destroy', investment_contract_det, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment Contract Det', new_investment_contract_det_path %>

app/views/investment_contract_dets/new.html.erb
<h1>New Investment Contract Det</h1>

<%= render 'form', investment_contract_det: @investment_contract_det %>

<%= link_to 'Back', investment_contract_dets_path %>

app/views/investment_contract_dets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idetcontribday:</strong>
  <%= @investment_contract_det.idetContribDay %>
</p>

<%= link_to 'Edit', edit_investment_contract_det_path(@investment_contract_det) %> |
<%= link_to 'Back', investment_contract_dets_path %>