config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :investment_contract_dets
  resources :car_rental_contract_dets
  resources :the_drivers
  resources :investment_contracts
  resources :car_rental_contracts
  resources :members
  resources :customers
  resources :drivers
  resources :cars
  resources :model_cars
  resources :brands
  devise_for :admins
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :model_cars
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :model_car
  has_many :car_rental_contract_dets
  has_many :car_rental_contracts, :through => :car_rental_contract_dets
# thuc the yeu investment_contract_dets
  has_many :investment_contract_dets
  has_many :investment_contracts, :through => :investment_contract_dets
end

app/models/car_rental_contract.rb
class CarRentalContract < ApplicationRecord
  has_many :customers
  has_many :car_rental_contract_dets
  has_many :cars, :through => :car_rental_contract_dets
  has_many :passenger
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :car_rental_contract
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :car_rental_contract_dets
  has_many :the_drivers
  has_many :model_cars, :through => :the_drivers
end

app/models/investment_contract.rb
class InvestmentContract < ApplicationRecord
  belongs_to :member
# thuc the yeu investment_contract_dets theo cach 2
  has_many :investment_contract_dets
  has_many :cars, :through => :investment_contract_dets
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :investment_contracts
end

app/models/model_car.rb
class ModelCar < ApplicationRecord
  belongs_to :brand
  has_many :cars
  has_many :the_drivers
  has_many :drivers, :through => :the_drivers
end

app/models/passenger.rb
class Passenger < ApplicationRecord
end

app/models/the_driver.rb
class TheDriver < ApplicationRecord
  belongs_to :driver
  belongs_to :model_car
end

app/controllers/model_cars_controller.rb
class ModelCarsController < ApplicationController
  before_action :set_model_car, only: [:show, :edit, :update, :destroy]

  # GET /model_cars
  # GET /model_cars.json
  def index
    @model_cars = ModelCar.all
  end

  # GET /model_cars/1
  # GET /model_cars/1.json
  def show
  end

  # GET /model_cars/new
  def new
    @model_car = ModelCar.new
  end

  # GET /model_cars/1/edit
  def edit
  end

  # POST /model_cars
  # POST /model_cars.json
  def create
    @model_car = ModelCar.new(model_car_params)

    respond_to do |format|
      if @model_car.save
        format.html { redirect_to @model_car, notice: 'Model car was successfully created.' }
        format.json { render :show, status: :created, location: @model_car }
      else
        format.html { render :new }
        format.json { render json: @model_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_cars/1
  # PATCH/PUT /model_cars/1.json
  def update
    respond_to do |format|
      if @model_car.update(model_car_params)
        format.html { redirect_to @model_car, notice: 'Model car was successfully updated.' }
        format.json { render :show, status: :ok, location: @model_car }
      else
        format.html { render :edit }
        format.json { render json: @model_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_cars/1
  # DELETE /model_cars/1.json
  def destroy
    @model_car.destroy
    respond_to do |format|
      format.html { redirect_to model_cars_url, notice: 'Model car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_car
      @model_car = ModelCar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_car_params
      params.require(:model_car).permit(:model, :noSeat, :factoryPrice)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/model_cars_helper.rb
module ModelCarsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/the_drivers_helper.rb
module TheDriversHelper
end

app/views/model_cars/_form.html.erb
<%= form_with(model: model_car, local: true) do |form| %>
  <% if model_car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model_car.errors.count, "error") %> prohibited this model_car from being saved:</h2>

      <ul>
      <% model_car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :noSeat %>
    <%= form.number_field :noSeat %>
  </div>

  <div class="field">
    <%= form.label :factoryPrice %>
    <%= form.text_field :factoryPrice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/model_cars/edit.html.erb
<h1>Editing Model Car</h1>

<%= render 'form', model_car: @model_car %>

<%= link_to 'Show', @model_car %> |
<%= link_to 'Back', model_cars_path %>

app/views/model_cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Model Cars</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Noseat</th>
      <th>Factoryprice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @model_cars.each do |model_car| %>
      <tr>
        <td><%= model_car.model %></td>
        <td><%= model_car.noSeat %></td>
        <td><%= model_car.factoryPrice %></td>
        <td><%= link_to 'Show', model_car %></td>
        <td><%= link_to 'Edit', edit_model_car_path(model_car) %></td>
        <td><%= link_to 'Destroy', model_car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model Car', new_model_car_path %>

app/views/model_cars/new.html.erb
<h1>New Model Car</h1>

<%= render 'form', model_car: @model_car %>

<%= link_to 'Back', model_cars_path %>

app/views/model_cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @model_car.model %>
</p>

<p>
  <strong>Noseat:</strong>
  <%= @model_car.noSeat %>
</p>

<p>
  <strong>Factoryprice:</strong>
  <%= @model_car.factoryPrice %>
</p>

<%= link_to 'Edit', edit_model_car_path(@model_car) %> |
<%= link_to 'Back', model_cars_path %>